language: ruby
bundler_args: --without development
rvm:
 - 1.9.2
 - 1.9.3
before_script:
 - cp config/database.yml.example config/database.yml
 - psql -c 'create database agileista_test;' -U postgres
script:
 - RAILS_ENV=test bundle exec rake db:migrate
 - bundle exec rake db:test:prepare
 - bundle exec rspec spec/
notifications:
  email:
    - lebreeze@gmail.com
