# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ca67ca27e2952e11add579f02e96ab2d4547e3adb0a06fae9ab9d1985faf1f7f74be4687324c4a48cce0936b97dd777cc4418fd175a579b1fd32ace590a3777

test:
  secret_key_base: ffbc07950336bbda8d2c930d62bdba30e712d514fa798e1f7bd47bb97c24e1fca0ad064bc4522fc280426b816f20bad7bd0af4b51e3ccc19fec1cc1d819a2dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
